
// Copyright 2012 Google Inc. All rights reserved.
// Container Version: null
(function(){

var data = {
"resource": {
  "version":"1",
  "macros":[
    
  ],
  "tags":[
    
  ],
  "predicates":[
    
  ],
  "rules":[
    
  ]
},
"runtime":[
[],






[]
]};

var ca=function(a){var b=aa;function c(){}c.prototype=b.prototype;a.wb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.tb=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var m=function(a,b){this.c=a;this.Ma=b};m.prototype.Ua=function(){return this.c};m.prototype.getType=m.prototype.Ua;m.prototype.getData=function(){return this.Ma};m.prototype.getData=m.prototype.getData;var ea=function(a){return"number"==typeof a&&0<=a&&isFinite(a)&&0==a%1||"string"==typeof a&&"-"!=a[0]&&a==""+parseInt(a,10)},aa=function(){this.F={};this.w=!1};aa.prototype.get=function(a){return this.F["dust."+a]};aa.prototype.set=function(a,b){!this.w&&(this.F["dust."+a]=b)};aa.prototype.has=function(a){return this.F.hasOwnProperty("dust."+a)};var fa=function(a){var b=[],c;for(c in a.F)a.F.hasOwnProperty(c)&&b.push(c.substr(5));return b};
aa.prototype.remove=function(a){!this.w&&delete this.F["dust."+a]};var t=function(a){this.H=new aa;this.a=[];a=a||[];for(var b in a)a.hasOwnProperty(b)&&(ea(b)?this.a[Number(b)]=a[Number(b)]:this.H.set(b,a[b]))};t.prototype.toString=function(){for(var a=[],b=0;b<this.a.length;b++){var c=this.a[b];null===c||void 0===c?a.push(""):a.push(c.toString())}return a.join(",")};t.prototype.set=function(a,b){if("length"==a){if(!ea(b))throw"RangeError: Length property must be a valid integer.";this.a.length=Number(b)}else ea(a)?this.a[Number(a)]=b:this.H.set(a,b)};
t.prototype.set=t.prototype.set;t.prototype.get=function(a){return"length"==a?this.a.length:ea(a)?this.a[Number(a)]:this.H.get(a)};t.prototype.get=t.prototype.get;t.prototype.o=function(){for(var a=fa(this.H),b=0;b<this.a.length;b++)a.push(b+"");return new t(a)};t.prototype.getKeys=t.prototype.o;t.prototype.remove=function(a){ea(a)?delete this.a[Number(a)]:this.H.remove(a)};t.prototype.remove=t.prototype.remove;t.prototype.pop=function(){return this.a.pop()};t.prototype.pop=t.prototype.pop;
t.prototype.push=function(a){return this.a.push.apply(this.a,Array.prototype.slice.call(arguments))};t.prototype.push=t.prototype.push;t.prototype.shift=function(){return this.a.shift()};t.prototype.shift=t.prototype.shift;t.prototype.splice=function(a,b,c){return new t(this.a.splice.apply(this.a,arguments))};t.prototype.splice=t.prototype.splice;t.prototype.unshift=function(a){return this.a.unshift.apply(this.a,Array.prototype.slice.call(arguments))};t.prototype.unshift=t.prototype.unshift;
t.prototype.has=function(a){return ea(a)&&this.a.hasOwnProperty(a)||this.H.has(a)};var u=function(a){this.A=a;this.a=new aa};u.prototype.add=function(a,b){this.a.set(a,b)};u.prototype.add=u.prototype.add;u.prototype.set=function(a,b){this.A&&this.A.has(a)?this.A.set(a,b):this.a.set(a,b)};u.prototype.set=u.prototype.set;u.prototype.get=function(a){return this.a.has(a)?this.a.get(a):this.A?this.A.get(a):void 0};u.prototype.get=u.prototype.get;u.prototype.has=function(a){return!!this.a.has(a)||!(!this.A||!this.A.has(a))};u.prototype.has=u.prototype.has;var z=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},ha=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1};var C=function(a,b){aa.call(this);this.qa=a;this.Sa=b};ca(C);C.prototype.toString=function(){return this.qa};C.prototype.getName=function(){return this.qa};C.prototype.getName=C.prototype.getName;C.prototype.o=function(){return new t(fa(this))};C.prototype.getKeys=C.prototype.o;C.prototype.b=function(a,b){return this.Sa.apply({j:function(){return a},evaluate:function(b){var c=a;return z(b)?ia(c,b):b},N:function(b){return ja(a,b)}},Array.prototype.slice.call(arguments,1))};C.prototype.invoke=C.prototype.b;
var ja=function(a,b){for(var c,d=0;d<b.length&&!(c=ia(a,b[d]),c instanceof m);d++);return c},ia=function(a,b){var c=a.get(String(b[0]));if(!(c&&c instanceof C))throw"Attempting to execute non-function "+b[0]+".";return c.b.apply(c,[a].concat(b.slice(1)))};var D=function(){aa.call(this)};ca(D);D.prototype.o=function(){return new t(fa(this))};D.prototype.getKeys=D.prototype.o;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var ka=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,la=function(a){if(null==a)return String(a);var b=ka.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},ma=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},E=function(a){if(!a||"object"!=la(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!ma(a,"constructor")&&!ma(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||ma(a,b)},G=function(a,b){var c=b||("array"==la(a)?[]:{}),d;for(d in a)if(ma(a,d)){var e=a[d];"array"==la(e)?("array"!=la(c[d])&&(c[d]=[]),c[d]=G(e,c[d])):E(e)?(E(c[d])||(c[d]={}),c[d]=G(e,c[d])):c[d]=e}return c};var oa=function(a){if(a instanceof t){for(var b=[],c=Number(a.get("length")),d=0;d<c;d++)a.has(d)&&(b[d]=oa(a.get(d)));return b}if(a instanceof D){var e={},f=a.o();c=Number(f.get("length"));for(d=0;d<c;d++)e[f.get(d)]=oa(a.get(f.get(d)));return e}return a instanceof C?function(){for(var b=Array.prototype.slice.call(arguments,0),c=0;c<b.length;c++)b[c]=pa(b[c]);return oa(a.b.apply(a,[{}].concat(b)))}:a},pa=function(a){if(z(a)){for(var b=[],c=0;c<a.length;c++)a.hasOwnProperty(c)&&(b[c]=pa(a[c]));return new t(b)}if(E(a)){var d=
new D,e;for(e in a)a.hasOwnProperty(e)&&d.set(e,pa(a[e]));return d}if("function"==typeof a)return new C("",function(b){for(var c=Array.prototype.slice.call(arguments,0),d=0;d<c.length;d++)c[d]=oa(this.evaluate(c[d]));return pa(a.apply(a,c))});var f=typeof a;if(null===a||"string"==f||"number"==f||"boolean"==f)return a};var qa={control:function(a,b){return new m(a,this.evaluate(b))},fn:function(a,b,c){var d=this.j(),e=this.evaluate(b);if(!(e instanceof t))throw"Error: non-List value given for Fn argument names.";var f=Array.prototype.slice.call(arguments,2);return new C(a,function(){return function(a){for(var b=new u(d),c=Array.prototype.slice.call(arguments,0),g=0;g<c.length;g++)if(c[g]=this.evaluate(c[g]),c[g]instanceof m)return c[g];var n=e.get("length");for(g=0;g<n;g++)g<c.length?b.set(e.get(g),c[g]):b.set(e.get(g),
void 0);b.set("arguments",new t(c));var k=ja(b,f);if(k instanceof m)return"return"==k.c?k.getData():k}}())},list:function(a){for(var b=new t,c=0;c<arguments.length;c++)b.push(this.evaluate(arguments[c]));return b},map:function(a){for(var b=new D,c=0;c<arguments.length-1;c+=2)b.set(this.evaluate(arguments[c]),this.evaluate(arguments[c+1]));return b},undefined:function(){}};var H=function(){this.oa=new u};H.prototype.s=function(a,b){var c=new C(a,b);c.w=!0;this.oa.set(a,c)};H.prototype.addInstruction=H.prototype.s;H.prototype.ha=function(a,b){qa.hasOwnProperty(a)&&this.s(b||a,qa[a])};H.prototype.addNativeInstruction=H.prototype.ha;H.prototype.f=function(a,b){var c=Array.prototype.slice.call(arguments,0),d=ia(this.oa,c);if(d instanceof m||d instanceof C||d instanceof t||d instanceof D||null===d||void 0===d||"string"==typeof d||"number"==typeof d||"boolean"==typeof d)return d};
H.prototype.execute=H.prototype.f;H.prototype.kb=function(a){for(var b=0;b<arguments.length;b++)this.f.apply(this,arguments[b])};H.prototype.run=H.prototype.kb;var ra=function(a){for(var b=[],c=Number(a.get("length")),d=0;d<c;d++)a.has(d)&&(b[d]=a.get(d));return b};var I={pb:"concat every filter forEach hasOwnProperty indexOf join lastIndexOf map pop push reduce reduceRight reverse shift slice some sort splice unshift toString".split(" ")},J=function(a){return Number(a.get("length"))};I.concat=function(a,b){for(var c=[],d=J(this),e=0;e<d;e++)c.push(this.get(e));for(e=1;e<arguments.length;e++)if(arguments[e]instanceof t)for(var f=arguments[e],g=J(f),h=0;h<g;h++)c.push(f.get(h));else c.push(arguments[e]);return new t(c)};
I.every=function(a,b){for(var c=J(this),d=0;d<J(this)&&d<c;d++)if(this.has(d)&&!b.b(a,this.get(d),d,this))return!1;return!0};I.filter=function(a,b){for(var c=J(this),d=[],e=0;e<J(this)&&e<c;e++)this.has(e)&&b.b(a,this.get(e),e,this)&&d.push(this.get(e));return new t(d)};I.forEach=function(a,b){for(var c=J(this),d=0;d<J(this)&&d<c;d++)this.has(d)&&b.b(a,this.get(d),d,this)};I.hasOwnProperty=function(a,b){return this.has(b)};
I.indexOf=function(a,b,c){var d=J(this),e=void 0===c?0:Number(c);0>e&&(e=Math.max(d+e,0));for(var f=e;f<d;f++)if(this.has(f)&&this.get(f)===b)return f;return-1};I.join=function(a,b){for(var c=[],d=J(this),e=0;e<d;e++)c.push(this.get(e));return c.join(b)};I.lastIndexOf=function(a,b,c){var d=J(this),e=d-1;void 0!==c&&(e=0>c?d+c:Math.min(c,e));for(var f=e;0<=f;f--)if(this.has(f)&&this.get(f)===b)return f;return-1};
I.map=function(a,b){for(var c=J(this),d=[],e=0;e<J(this)&&e<c;e++)this.has(e)&&(d[e]=b.b(a,this.get(e),e,this));return new t(d)};I.pop=function(){return this.pop()};I.push=function(a,b){return this.push.apply(this,Array.prototype.slice.call(arguments,1))};
I.reduce=function(a,b,c){var d=J(this),e,f;if(void 0!==c)e=c,f=0;else{if(0==d)throw"TypeError: Reduce on List with no elements.";for(var g=0;g<d;g++)if(this.has(g)){e=this.get(g);f=g+1;break}if(g==d)throw"TypeError: Reduce on List with no elements.";}for(g=f;g<d;g++)this.has(g)&&(e=b.b(a,e,this.get(g),g,this));return e};
I.reduceRight=function(a,b,c){var d=J(this),e,f;if(void 0!==c)e=c,f=d-1;else{if(0==d)throw"TypeError: ReduceRight on List with no elements.";for(var g=1;g<=d;g++)if(this.has(d-g)){e=this.get(d-g);f=d-(g+1);break}if(g>d)throw"TypeError: ReduceRight on List with no elements.";}for(g=f;0<=g;g--)this.has(g)&&(e=b.b(a,e,this.get(g),g,this));return e};I.reverse=function(){for(var a=ra(this),b=a.length-1,c=0;0<=b;b--,c++)a.hasOwnProperty(b)?this.set(c,a[b]):this.remove(c);return this};I.shift=function(){return this.shift()};
I.slice=function(a,b,c){var d=J(this);void 0===b&&(b=0);b=0>b?Math.max(d+b,0):Math.min(b,d);c=void 0===c?d:0>c?Math.max(d+c,0):Math.min(c,d);c=Math.max(b,c);for(var e=[],f=b;f<c;f++)e.push(this.get(f));return new t(e)};I.some=function(a,b){for(var c=J(this),d=0;d<J(this)&&d<c;d++)if(this.has(d)&&b.b(a,this.get(d),d,this))return!0;return!1};
I.sort=function(a,b){var c=ra(this);void 0===b?c.sort():c.sort(function(c,d){return Number(b.b(a,c,d))});for(var d=0;d<c.length;d++)c.hasOwnProperty(d)?this.set(d,c[d]):this.remove(d)};I.splice=function(a,b,c,d){return this.splice.apply(this,Array.prototype.splice.call(arguments,1,arguments.length-1))};I.toString=function(){return this.toString()};I.unshift=function(a,b){return this.unshift.apply(this,Array.prototype.slice.call(arguments,1))};var N={P:{ADD:0,AND:1,APPLY:2,ASSIGN:3,BREAK:4,CASE:5,CONTINUE:6,CONTROL:49,CREATE_ARRAY:7,CREATE_OBJECT:8,DEFAULT:9,DEFN:50,DIVIDE:10,DO:11,EQUALS:12,EXPRESSION_LIST:13,FN:51,FOR:14,FOR_IN:47,GET:15,GET_CONTAINER_VARIABLE:48,GET_INDEX:16,GET_PROPERTY:17,GREATER_THAN:18,GREATER_THAN_EQUALS:19,IDENTITY_EQUALS:20,IDENTITY_NOT_EQUALS:21,IF:22,LESS_THAN:23,LESS_THAN_EQUALS:24,MODULUS:25,MULTIPLY:26,NEGATE:27,NOT:28,NOT_EQUALS:29,NULL:45,OR:30,PLUS_EQUALS:31,POST_DECREMENT:32,POST_INCREMENT:33,PRE_DECREMENT:34,
PRE_INCREMENT:35,QUOTE:46,RETURN:36,SET_PROPERTY:43,SUBTRACT:37,SWITCH:38,TERNARY:39,TYPEOF:40,UNDEFINED:44,VAR:41,WHILE:42}},sa="charAt concat indexOf lastIndexOf match replace search slice split substring toLowerCase toLocaleLowerCase toString toUpperCase toLocaleUpperCase trim".split(" "),ta=new m("break"),ua=new m("continue");N.add=function(a,b){return this.evaluate(a)+this.evaluate(b)};N.and=function(a,b){return this.evaluate(a)&&this.evaluate(b)};
N.apply=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!(c instanceof t))throw"Error: Non-List argument given to Apply instruction.";if(null===a||void 0===a)throw"TypeError: Can't read property "+b+" of "+a+".";if("boolean"==typeof a||"number"==typeof a){if("toString"==b)return a.toString();throw"TypeError: "+a+"."+b+" is not a function.";}if("string"==typeof a){if(0<=ha(sa,b))return pa(a[b].apply(a,ra(c)));throw"TypeError: "+b+" is not a function";}if(a instanceof t){if(a.has(b)){var d=
a.get(b);if(d instanceof C){var e=ra(c);e.unshift(this.j());return d.b.apply(d,e)}throw"TypeError: "+b+" is not a function";}if(0<=ha(I.pb,b))return e=ra(c),e.unshift(this.j()),I[b].apply(a,e)}if(a instanceof C||a instanceof D){if(a.has(b)){d=a.get(b);if(d instanceof C)return e=ra(c),e.unshift(this.j()),d.b.apply(d,e);throw"TypeError: "+b+" is not a function";}if("toString"==b)return a instanceof C?a.getName():a.toString();if("hasOwnProperty"==b)return a.has.apply(a,ra(c))}throw"TypeError: Object has no '"+
b+"' property.";};N.assign=function(a,b){a=this.evaluate(a);if("string"!=typeof a)throw"Invalid key name given for assignment.";var c=this.j();if(!c.has(a))throw"Attempting to assign to undefined value "+b;var d=this.evaluate(b);c.set(a,d);return d};N["break"]=function(){return ta};N["case"]=function(a){for(var b=this.evaluate(a),c=0;c<b.length;c++){var d=this.evaluate(b[c]);if(d instanceof m)return d}};N["continue"]=function(){return ua};
N.Na=function(a,b,c){var d=new t;b=this.evaluate(b);for(var e=0;e<b.length;e++)d.push(b[e]);var f=[N.P.FN,a,d].concat(Array.prototype.splice.call(arguments,2,arguments.length-2));this.j().set(a,this.evaluate(f))};N.Oa=function(a,b){return this.evaluate(a)/this.evaluate(b)};N.Pa=function(a,b){return this.evaluate(a)==this.evaluate(b)};N.Qa=function(a){for(var b,c=0;c<arguments.length;c++)b=this.evaluate(arguments[c]);return b};
N.Ta=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);var d=this.j();if("string"==typeof b)for(var e=0;e<b.length;e++){d.set(a,e);var f=this.N(c);if(f instanceof m){if("break"==f.c)break;if("return"==f.c)return f}}else if(b instanceof D||b instanceof t||b instanceof C){var g=b.o(),h=Number(g.get("length"));for(e=0;e<h;e++)if(d.set(a,g.get(e)),f=this.N(c),f instanceof m){if("break"==f.c)break;if("return"==f.c)return f}}};N.get=function(a){return this.j().get(this.evaluate(a))};
N.na=function(a,b){var c;a=this.evaluate(a);b=this.evaluate(b);if(void 0===a||null===a)throw"TypeError: cannot access property of "+a+".";a instanceof D||a instanceof t||a instanceof C?c=a.get(b):"string"==typeof a&&("length"==b?c=a.length:ea(b)&&(c=a[b]));return c};N.Va=function(a,b){return this.evaluate(a)>this.evaluate(b)};N.Wa=function(a,b){return this.evaluate(a)>=this.evaluate(b)};N.Xa=function(a,b){return this.evaluate(a)===this.evaluate(b)};N.Ya=function(a,b){return this.evaluate(a)!==this.evaluate(b)};
N["if"]=function(a,b,c){var d=[];this.evaluate(a)?d=this.evaluate(b):c&&(d=this.evaluate(c));var e=this.N(d);if(e instanceof m)return e};N.ab=function(a,b){return this.evaluate(a)<this.evaluate(b)};N.bb=function(a,b){return this.evaluate(a)<=this.evaluate(b)};N.cb=function(a,b){return this.evaluate(a)%this.evaluate(b)};N.multiply=function(a,b){return this.evaluate(a)*this.evaluate(b)};N.eb=function(a){return-this.evaluate(a)};N.fb=function(a){return!this.evaluate(a)};
N.gb=function(a,b){return this.evaluate(a)!=this.evaluate(b)};N["null"]=function(){return null};N.or=function(a,b){return this.evaluate(a)||this.evaluate(b)};N.ta=function(a,b){var c=this.evaluate(a);this.evaluate(b);return c};N.ua=function(a){return this.evaluate(a)};N.quote=function(a){return Array.prototype.slice.apply(arguments)};N["return"]=function(a){return new m("return",this.evaluate(a))};
N.setProperty=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(null===a||void 0===a)throw"TypeError: Can't set property "+b+" of "+a+".";(a instanceof C||a instanceof t||a instanceof D)&&a.set(b,c);return c};N.ob=function(a,b){return this.evaluate(a)-this.evaluate(b)};
N["switch"]=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!z(b)||!z(c))throw"Error: Malformed switch instruction.";for(var d,e=!1,f=0;f<b.length;f++)if(e||a===this.evaluate(b[f]))if(d=this.evaluate(c[f]),d instanceof m){var g=d.c;if("break"==g)return;if("return"==g||"continue"==g)return d}else e=!0;if(c.length==b.length+1&&(d=this.evaluate(c[c.length-1]),d instanceof m&&("return"==d.c||"continue"==d.c)))return d};
N.qb=function(a,b,c){return this.evaluate(a)?this.evaluate(b):this.evaluate(c)};N["typeof"]=function(a){a=this.evaluate(a);return a instanceof C?"function":typeof a};N.undefined=function(){};N["var"]=function(a){for(var b=this.j(),c=0;c<arguments.length;c++){var d=arguments[c];"string"!=typeof d||b.add(d,void 0)}};
N["while"]=function(a,b,c,d){var e,f=this.evaluate(d);if(this.evaluate(c)&&(e=this.N(f),e instanceof m)){if("break"==e.c)return;if("return"==e.c)return e}for(;this.evaluate(a);){e=this.N(f);if(e instanceof m){if("break"==e.c)break;if("return"==e.c)return e}this.evaluate(b)}};var P=function(){this.pa=!1;this.C=new H;this.D=new D;va(this);this.f([N.P.VAR,"gtmUtils"]);this.f([N.P.ASSIGN,"gtmUtils",this.D]);this.pa=!0};P.prototype.$a=function(){return this.pa};P.prototype.isInitialized=P.prototype.$a;P.prototype.f=function(a){return this.C.f.apply(this.C,a)};P.prototype.execute=P.prototype.f;
var va=function(a){function b(a,b){e.C.ha(a,String(b))}function c(a,b){e.C.s(String(d[a]),b)}var d=N.P,e=a;b("control",d.CONTROL);b("fn",d.FN);b("list",d.CREATE_ARRAY);b("map",d.CREATE_OBJECT);b("undefined",d.UNDEFINED);c("ADD",N.add);c("AND",N.and);c("APPLY",N.apply);c("ASSIGN",N.assign);c("BREAK",N["break"]);c("CASE",N["case"]);c("CONTINUE",N["continue"]);c("DEFAULT",N["case"]);c("DEFN",N.Na);c("DIVIDE",N.Oa);c("EQUALS",N.Pa);c("EXPRESSION_LIST",N.Qa);c("FOR_IN",N.Ta);c("GET",N.get);c("GET_INDEX",
N.na);c("GET_PROPERTY",N.na);c("GREATER_THAN",N.Va);c("GREATER_THAN_EQUALS",N.Wa);c("IDENTITY_EQUALS",N.Xa);c("IDENTITY_NOT_EQUALS",N.Ya);c("IF",N["if"]);c("LESS_THAN",N.ab);c("LESS_THAN_EQUALS",N.bb);c("MODULUS",N.cb);c("MULTIPLY",N.multiply);c("NEGATE",N.eb);c("NOT",N.fb);c("NOT_EQUALS",N.gb);c("NULL",N["null"]);c("OR",N.or);c("POST_DECREMENT",N.ta);c("POST_INCREMENT",N.ta);c("PRE_DECREMENT",N.ua);c("PRE_INCREMENT",N.ua);c("QUOTE",N.quote);c("RETURN",N["return"]);c("SET_PROPERTY",N.setProperty);
c("SUBTRACT",N.ob);c("SWITCH",N["switch"]);c("TERNARY",N.qb);c("TYPEOF",N["typeof"]);c("VAR",N["var"]);c("WHILE",N["while"])};P.prototype.Ba=function(a){this.C.s(String(N.P.GET_CONTAINER_VARIABLE),a)};P.prototype.addContainerVariableInstruction=P.prototype.Ba;P.prototype.Ca=function(a,b){for(var c=new D,d=b.o(),e=Number(d.get("length")),f=0;f<e;f++){var g=d.get(f);c.set(g,b.get(g))}c.w=!0;b.set("base",c);this.D.set(a,b)};P.prototype.addLibrary=P.prototype.Ca;
P.prototype.s=function(a,b){this.C.s(a,b)};P.prototype.addInstruction=P.prototype.s;P.prototype.Ra=function(a){a&&this.f([a,this.D]);for(var b=this.D.o(),c=Number(b.get("length")),d=0;d<c;d++){var e=b.get(d);this.D.get(e).w=!0}this.D.w=!0};P.prototype.finalize=P.prototype.Ra;var wa=function(){this.T={}};wa.prototype.get=function(a){return this.T.hasOwnProperty(a)?this.T[a]:void 0};wa.prototype.add=function(a,b){if(this.T.hasOwnProperty(a))throw"Attempting to add a function which already exists: "+a+".";var c=new C(a,function(){for(var a=Array.prototype.slice.call(arguments,0),c=0;c<a.length;c++)a[c]=this.evaluate(a[c]);return b.apply(this,a)});c.w=!0;this.T[a]=c};wa.prototype.addAll=function(a){for(var b in a)a.hasOwnProperty(b)&&this.add(b,a[b])};var Q=window,R=document,xa=function(a,b){var c=Q[a];Q[a]=void 0===c?b:c;return Q[a]},ya=function(a){var b=R.getElementsByTagName("script")[0]||R.body||R.head;b.parentNode.insertBefore(a,b)},za=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},Aa=function(a,b,c){var d=R.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;za(d,b);c&&(d.onerror=c);ya(d);return d},Ca=function(a,b){var c=
R.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";ya(c);za(c,b);void 0!==a&&(c.src=a)},Da=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},Ea=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},U=function(a){Q.setTimeout(a,0)},Fa=function(a){return a&&a.attributes&&a.attributes.id?a.attributes.id.value:null};var Ha=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(decodeURIComponent(e[0]).replace(/\+/g," ")==b)return decodeURIComponent(e.slice(1).join("=")).replace(/\+/g," ")}},Ia=function(a,b,c,d,e){var f,g=a.protocol||Q.location.protocol;g=g.replace(":","").toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||Q.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;
case "port":f=String(1*(a.hostname?a.port:Q.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var p=f.split("/");0<=ha(d||[],p[p.length-1])&&(p[p.length-1]="");f=p.join("/");break;case "query":f=a.search.replace("?","");e&&(f=Ha(f,e));break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Ja=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},Ka=function(a){var b=
R.createElement("a");a&&(b.href=a);return b};var Na=function(){this.sa=new P;var a=new wa;a.addAll(La());Ma(this,function(b){return a.get(b)})},La=function(){return{callInWindow:Oa,getCurrentUrl:Pa,getInWindow:Qa,getReferrer:Ra,getUrlComponent:Ta,getUrlFragment:Ua,isPlainObject:Va,loadIframe:Wa,loadJavaScript:Xa,removeUrlFragment:Ya,replaceAll:Za,sendTrackingBeacon:$a,setInWindow:ab}};Na.prototype.f=function(a){return this.sa.f(a)};Na.prototype.execute=Na.prototype.f;var Ma=function(a,b){a.sa.s("require",b)};
function Oa(a,b){for(var c=a.split("."),d=Q,e=d[c[0]],f=1;e&&f<c.length;f++)d=e,e=e[c[f]];if("function"==la(e)){var g=[];for(f=1;f<arguments.length;f++)g.push(oa(arguments[f]));e.apply(d,g)}}function Pa(){return Q.location.href}function Qa(a,b,c){for(var d=a.split("."),e=Q,f=0;f<d.length-1;f++)if(e=e[d[f]],void 0===e||null===e)return;b&&(void 0===e[d[f]]||c&&!e[d[f]])&&(e[d[f]]=oa(b));return pa(e[d[f]])}function Ra(){return R.referrer}
function Ta(a,b,c,d,e){var f;if(d&&d instanceof t){f=[];for(var g=Number(d.get("length")),h=0;h<g;h++){var p=d.get(h);"string"==typeof p&&f.push(p)}}return Ia(Ka(a),b,c,f,e)}function Ua(a){return Ia(Ka(a),"fragment")}function Va(a){return a instanceof D}function Wa(a,b){var c=this.j();Ca(a,function(){b instanceof C&&b.b(c)})}var bb={};
function Xa(a,b,c,d){var e=this.j(),f=function(){b instanceof C&&b.b(e)},g=function(){c instanceof C&&c.b(e)};d?bb[d]?(bb[d].onSuccess.push(f),bb[d].onFailure.push(g)):(bb[d]={onSuccess:[f],onFailure:[g]},Aa(a,function(){for(var a=bb[d].onSuccess,b=0;b<a.length;b++)U(a[b]);a.push=function(a){U(a);return 0}},function(){for(var a=bb[d].onFailure,b=0;b<a.length;b++)U(a[b]);bb[d]=null})):Aa(a,f,g)}function Ya(a){return Ja(Ka(a))}function Za(a,b,c){return a.replace(new RegExp(b,"g"),c)}
function $a(a,b,c){var d=this.j();Da(a,function(){b instanceof C&&b.b(d)},function(){c instanceof C&&c.b(d)})}function ab(a,b,c){for(var d=a.split("."),e=Q,f=0;f<d.length-1;f++)if(e=e[d[f]],void 0===e)return!1;return void 0===e[d[f]]||c?(e[d[f]]=oa(b),!0):!1};var wb,xb=[],yb=[],zb=[],Ab=[],Bb={},Cb=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";if(Bb[b]){var c={},d;for(d in a)a.hasOwnProperty(d)&&0===d.indexOf("vtp_")&&(c[d]=a[d]);return Bb[b](c)}var e=new D;for(d in a)a.hasOwnProperty(d)&&0===d.indexOf("vtp_")&&e.set(d.substr(4),pa(a[d]));var f=wb([b,e]);f instanceof m&&"return"==f.c&&(f=f.getData());return oa(f)},Eb=function(a,b,c){var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=Db(a[e],b,c));return d},
Db=function(a,b,c){if(z(a))switch(a[0]){case "function_id":return a[1];case "list":for(var d=[],e=1;e<a.length;e++)d.push(Db(a[e],b,c));return d;case "macro":var f=a[1];if(b[f])throw Error("Macro cycle detected. Resolving macro "+f+"results in it resolving itself.");if(xb[f])return b[f]=!0,d=Cb(Eb(xb[f],b,c)),b[f]=!1,d;throw Error("Attempting to resolve unknown macro reference "+f+".");case "map":d={};for(e=1;e<a.length;e+=2)d[Db(a[e],b,c)]=Db(a[e+1],b,c);return d;case "template":d=[];for(e=1;e<a.length;e++)d.push(Db(a[e],
b,c));return d.join("");case "escape":d=Db(a[1],b,c);for(e=2;e<a.length;e++)V[a[e]]&&(d=V[a[e]](d));return d;default:throw"Error: Attempting to expand unknown Value type: "+a[0]+".";}return a};var Fb=null,Gb,Jb=function(a){function b(a){for(var b=0;b<a.length;b++)d[a[b]]=!0}var c=[],d=[];Fb=Hb(a);for(var e=0;e<yb.length;e++){var f=yb[e],g=Ib(f);if(g){for(var h=f.add||[],p=0;p<h.length;p++)c[h[p]]=!0;b(f.block||[])}else null===g&&b(f.block||[])}var l=[];for(e=0;e<Ab.length;e++)c[e]&&!d[e]&&(l[e]=!0);return l},Ib=function(a){for(var b=a["if"]||[],c=0;c<b.length;c++){var d=Fb(b[c]);if(!d)return null===d?null:!1}var e=a.unless||[];for(c=0;c<e.length;c++){d=Fb(e[c]);if(null===d)return null;
if(d)return!1}return!0},Hb=function(a){var b=[];return function(c){if(void 0!==b[c])return b[c];var d=zb[c],e=null;if(a(d))e=!1;else try{e=Gb(Eb(d,[],a))}catch(f){}return b[c]=null===e?e:!!e}};var Kb={},Lb=null;Kb.I="UA-109338366-1";var Mb=null,Nb={};var Ob=function(){},Pb=function(a){return"function"==typeof a},Qb=function(a){return"string"==la(a)},Rb=function(a){return"number"==la(a)&&!isNaN(a)},Sb=function(a){return!!a&&("[object Arguments]"==Object.prototype.toString.call(a)||Object.prototype.hasOwnProperty.call(a,"callee"))},Tb=function(a){return Math.round(Number(a))||0},Ub=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Vb=function(a){var b=[];if(z(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Wb=function(a){return a?
a.replace(/^\s+|\s+$/g,""):""},Xb=function(a,b){if(!Rb(a)||!Rb(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Yb=function(){this.prefix="gtm.";this.values={}};Yb.prototype.set=function(a,b){this.values[this.prefix+a]=b};Yb.prototype.get=function(a){return this.values[this.prefix+a]};Yb.prototype.contains=function(a){return void 0!==this.get(a)};
var Zb=function(){var a=Lb.sequence||0;Lb.sequence=a+1;return a},$b=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},ac=function(a){var b=!1;return function(){if(!b)try{a()}catch(c){}b=!0}};var bc=function(a,b){},cc=function(a,b){},dc=function(a,b){},ec=function(a,b){},fc=function(){};var ic=!1,jc=0,kc=[];function lc(a){if(!ic){var b=R.createEventObject,c="complete"==R.readyState,d="interactive"==R.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ic=!0;for(var e=0;e<kc.length;e++)U(kc[e])}kc.push=function(){for(var a=0;a<arguments.length;a++)U(arguments[a]);return 0}}}function mc(){if(!ic&&140>jc){jc++;try{R.documentElement.doScroll("left"),lc()}catch(a){Q.setTimeout(mc,50)}}};var nc=function(){var a=function(a){return{toString:function(){return a}}};return{R:a("function"),rb:a("live_only"),sb:a("tag_id")}}();var oc=new Yb,pc={},rc={set:function(a,b){G(qc(a,b),pc)},get:function(a){return X(a,2)},reset:function(){oc=new Yb;pc={}}},X=function(a,b){return 2!=b?oc.get(a):sc(a)},sc=function(a,b,c){var d=a.split(".");var e=function(a,b){for(var c=0;void 0!==a&&c<d.length;c++)a=a[d[c]];return void 0!==a||1<c?a:b.length?e(tc(b.pop()),b):uc(d)};return e(pc.eventModel,[b,c]);return uc(d)},uc=function(a){for(var b=pc,c=0;c<a.length&&void 0!==b;c++)b=b[a[c]];
return b};var tc=function(a){if(a){var b=uc(["gtag","targets",a]);return E(b)?b:void 0}},vc=function(a,b){function c(a){if(a)for(var b in a)a.hasOwnProperty(b)&&(d[b]=null)}var d={};c(pc);delete d.eventModel;c(tc(a));c(tc(b));c(pc.eventModel);var e=[],f;for(f in d)d.hasOwnProperty(f)&&e.push(f);return e};
var wc=function(a,b){oc.set(a,b);G(qc(a,b),pc)},qc=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var xc=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),yc={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},zc={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Ac=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c};
var Bc=function(){var a=X("gtm.whitelist");a="gtagua gtagaw gtagfl e v oid op cn css ew eq ge gt lc le lt re sw um".split(" ");var b=a&&Ac(Vb(a),yc),c=X("gtm.blacklist")||
X("tagTypeBlacklist")||[];var d=c&&Ac(Vb(c),zc),e={};return function(f){var g=f&&f[nc.R];if(!g||"string"!=typeof g)return!0;g=g.replace(/_/g,"");if(void 0!==e[g])return e[g];var h=[],p=!0;if(a)a:{if(0>ha(b,g))if(h&&0<h.length)for(var l=0;l<h.length;l++){if(0>ha(b,h[l])){p=
!1;break a}}else{p=!1;break a}p=!0}var n=!1;if(c){var k;if(!(k=0<=ha(d,g)))a:{for(var q=h||[],w=new Yb,B=0;B<d.length;B++)w.set(d[B],!0);for(B=0;B<q.length;B++)if(w.get(q[B])){k=!0;break a}k=!1}n=k}return e[g]=!p||n}};function Cc(a){var b=0,c=0,d=!1;return{add:function(){c++;return ac(function(){b++;d&&b>=c&&a()})},Ea:function(){d=!0;b>=c&&a()}}}var Dc=!1;var Ec=function(a,b){var c={};c[nc.R]="__"+a;for(var d in b)b.hasOwnProperty(d)&&(c["vtp_"+d]=b[d]);for(d in void 0)(void 0).hasOwnProperty(d)&&(c[d]=(void 0)[d]);Ab.push(c);return Ab.length-1};var Fc=null,Gc={},Hc={},Ic;function Jc(){Fc=Fc||!Lb.gtagRegistered;Lb.gtagRegistered=!0;return Fc}var Kc=function(a,b){var c={event:a};b&&(c.eventModel=G(b,void 0),b.event_callback&&(c.eventCallback=b.event_callback),b.event_timeout&&(c.eventTimeout=b.event_timeout));return c};
function Lc(a){if(void 0===Hc[a]){var b=a.split("-"),c;if("UA"==b[0])c=Ec("gtagua",{trackingId:a});else if("AW"==b[0])c=Ec("gtagaw",{conversionId:a});else if("DC"==b[0])c=Ec("gtagfl",{targetId:a});else{dc("Unknown target: %s",a);return}if(!Ic){var d={name:"send_to",dataLayerVersion:2},e={};e[nc.R]="__v";for(var f in d)d.hasOwnProperty(f)&&(e["vtp_"+f]=d[f]);xb.push(e);Ic=["macro",xb.length-1]}var g={arg0:Ic,arg1:a,ignore_case:!1};g[nc.R]="_lc";zb.push(g);var h={"if":[zb.length-1],add:[c]};h["if"]&&
(h.add||h.block)&&yb.push(h);Hc[a]=c}}
var Oc={event:function(a){var b=a[1];if(!Qb(b)||3<a.length)Mc("event","[string, Object]",a);else{var c;if(2<a.length){if(!E(a[2]))return;c=a[2]}var d=Kc(b,c);var e;var f=c,g=X("gtag.fields.send_to",2);Qb(g)||(g="send_to");var h=f&&f[g];void 0===h&&(h=X(g,2),void 0===h&&(h="default"));if(Qb(h)||z(h)){for(var p=h.toString().replace(/\s+/g,"").split(","),l=[],n=0;n<p.length;n++)0<=p[n].indexOf("-")?l.push(p[n]):l=l.concat(Gc[p[n]]||[]);e=l}else dc('Invalid "send_to" value: %s',
h),e=void 0;if(!e)return;var k=Jc();k||Nc();for(var q=0;k&&q<e.length;q++)Lc(e[q]);d.eventModel=d.eventModel||{};0<e.length?d.eventModel.send_to=e.join():delete d.eventModel.send_to;return d}},set:function(a){var b;2==a.length&&E(a[1])?b=G(a[1],void 0):3==a.length&&Qb(a[1])?(b={},b[a[1]]=a[2]):Mc("set","[string, Object] or [string, string, string]",a);if(b)return b.eventModel=G(b,void 0),b.event="gtag.set",b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js",
"gtm.start":a[1].getTime()};Mc("js","[js, Date]",a)},config:function(a){var b=a[1],c=a[2]||{};if(2>a.length||!Qb(b)||!E(c)){Mc("config","[string, object]",a);return}Jc()?Lc(b):Nc();for(var d in Gc)if(Gc.hasOwnProperty(d)){var e=ha(Gc[d],b);0<=e&&Gc[d].splice(e,1)}var f=c.groups||"default";f=f.toString().split(",");for(var g=0;g<f.length;g++)Gc[f[g]]=Gc[f[g]]||[],Gc[f[g]].push(b);delete c.groups;wc("gtag.targets."+b,void 0);wc("gtag.targets."+b,G(c,void 0));bc('GTAG Command: "config", target: %s, configuration: %s',
b,c);return Kc("gtag.config",{send_to:b});}};function Mc(a,b,c){dc("Ignored %s command. Invalid arguments found.",a);dc("  Expected: %s",b);dc("  Actual:   %s",c)}var Nc=ac(function(){cc("GTAG script is installed twice.")});var Pc=!1,Qc=[];function Rc(){if(!Pc){Pc=!0;for(var a=0;a<Qc.length;a++)U(Qc[a])}};var Sc=[],Tc=!1,Uc=function(a){var b=a.eventCallback,c=ac(function(){Pb(b)&&U(function(){b(Kb.I)})}),d=a.eventTimeout;d&&Q.setTimeout(c,Number(d));return c},Vc=function(){var a=!1;for(ec("Processing commands (%s)",Sc.length);!Tc&&0<Sc.length;){Tc=!0;delete pc.eventModel;var b=Sc.shift();if(Pb(b)){ec("Processing custom method: %s",b);try{b.call(rc)}catch(F){dc("Error occurred during custom method invocation: %s",F)}}else if(z(b)){ec("Processing data layer command: %s",b);var c=b;if(Qb(c[0])){var d=
c[0].split("."),e=d.pop(),f=c.slice(1),g=X(d.join("."),2);if(void 0!==g&&null!==g)try{g[e].apply(g,f)}catch(F){dc("Error occurred during command processing: %s",F)}}}else{if(Sb(b)){ec("Processing GTAG command: %s",b);a:{var h=b;if(h.length)if(Qb(h[0])){var p=Oc[h[0]];if(p){b=p(h);break a}dc("Unknown command name: %s",h)}else dc("Invalid command name: %s",h);else dc("Command name not specified.");b=void 0}if(!b){Tc=!1;fc();continue}}else ec("Processing data layer push: %s",b);var l,n=void 0,k=b,q=
k._clear;for(n in k)k.hasOwnProperty(n)&&"_clear"!==n&&(q&&wc(n,void 0),wc(n,k[n]));var w=!1,B=k.event;if(B){l=Zb();Mb=B;k["gtm.uniqueEventId"]||wc("gtm.uniqueEventId",l);var v=Uc(k);a:{var S=l,L=B,ba=v;switch(L){case "gtm.js":if(Dc){w=!1;break a}Dc=!0}var A={id:S,name:L,Ga:ba||Ob,ca:Bc()};A.wa=Jb(A.ca);for(var O=A,T=!1,y=Cc(O.Ga),x=0;x<O.wa.length;x++)if(O.wa[x]){var r=Ab[x];if(O.ca(r))cc("Tag blacklisted: %s",r);else{var M=y.add();try{var K=Eb(r,[],O.ca);K.vtp_gtmOnSuccess=M;K.vtp_gtmOnFailure=
M;Cb(K);bc("Tag fired: %s",r)}catch(F){dc("Tag exception: %s - %s",r,F);M();continue}T=!0}}y.Ea();w=T}w||bc("No tags for event: %s  were fired.",B)}Mb=null;a=w||a}Tc=!1;fc()}fc();return!a},Wc=function(){return Vc()};var Xc=new Yb;
function Yc(a){var b=a.arg0,c=a.arg1;switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_ew":var d,e;d=String(b);e=String(c);var f=d.length-e.length;return 0<=f&&d.indexOf(e,f)==f;case "_eq":return String(b)==String(c);case "_ge":return Number(b)>=Number(c);case "_gt":return Number(b)>Number(c);case "_lc":var g;g=b.toString().split(",");return 0<=ha(g,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":var h;var p=a.ignore_case?
"i":void 0;try{var l=String(c)+p,n=Xc.get(l);n||(n=new RegExp(c,p),Xc.set(l,n));h=n.test(b)}catch(k){h=!1}return h;case "_sw":return 0==String(b).indexOf(String(c))}return!1};function Zc(a,b,c,d){return(d||"https:"==Q.location.protocol?a:b)+c}function $c(a,b){for(var c=b||(a instanceof t?new t:new D),d=a.o(),e=Number(d.get("length")),f=0;f<e;f++){var g=d.get(f);if(a.has(g)){var h=a.get(g);h instanceof t?(c.get(g)instanceof t||c.set(g,new t),$c(h,c.get(g))):h instanceof D?(c.get(g)instanceof D||c.set(g,new D),$c(h,c.get(g))):c.set(g,h)}}return c}function ad(){return Kb.I}function bd(){return(new Date).getTime()}function cd(a,b){return pa(X(a,b||2))}
function dd(){return Mb}function ed(a){var b=R.createElement("div");b.innerHTML="A<div>"+('<a href="'+a+'"></a>')+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c[0].href}function fd(a){return Tb(oa(a))}function gd(a){return null===a?"null":void 0===a?"undefined":a.toString()}function hd(a,b){return Xb(a,b)}
function id(a,b,c){if(!(a instanceof t))return null;for(var d=new D,e=!1,f=a.get("length"),g=0;g<f;g++){var h=a.get(g);h instanceof D&&h.has(b)&&h.has(c)&&(d.set(h.get(b),h.get(c)),e=!0)}return e?d:null}var jd=function(){var a=new wa;a.addAll(La());a.addAll({buildSafeUrl:Zc,decodeHtmlUrl:ed,copy:$c,generateUniqueNumber:Zb,getContainerId:ad,getCurrentTime:bd,getDataLayerValue:cd,getEventName:dd,makeInteger:fd,makeString:gd,randomInteger:hd,tableToMap:id});return function(b){return a.get(b)}};var kd=new Na;var ld=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var md=function(a){return encodeURIComponent(a)};var nd=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},od=function(a,b){G(a,b)},pd=function(a){return Tb(a)},qd=function(a,b){return ha(a,b)};var rd=/(^|\.)doubleclick\.net$/i,sd=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,td=function(a){for(var b=String(R.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=Wb(e[0]);if(f&&f==a){var g=Wb(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},ud=function(a,b,c,d,e){b=encodeURIComponent(b);var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");var g,h;if("auto"==d){var p=Ia(Q.location,"host",!0).split(".");if(4==p.length&&/^[0-9]*$/.exec(p[3]))h=
["none"];else{for(var l=[],n=p.length-2;0<=n;n--)l.push(p.slice(n).join("."));l.push("none");h=l}}else h=[d||"none"];g=h;for(var k=R.cookie,q=0;q<g.length;q++){var w=f,B=g[q],v=c;if(rd.test(Q.location.hostname)||"/"==v&&sd.test(B))break;"none"!=g[q]&&(w+="domain="+g[q]+";");R.cookie=w;if(k!=R.cookie||0<=ha(td(a),b))break}};
var vd=function(a){return!(void 0===a||null===a||0===(a+"").length)},wd=function(a,b){var c;if(2===b.m)return a("ord",Xb(1E11,1E13)),!0;if(3===b.m)return a("ord","1"),a("num",Xb(1E11,1E13)),!0;if(4===b.m)return vd(b.sessionId)&&a("ord",b.sessionId),!0;if(5===b.m)c="1";else if(6===b.m)c=b.va;else return!1;vd(c)&&a("qty",c);vd(b.Y)&&a("cost",b.Y);vd(b.fa)&&a("ord",b.fa);return!0},xd=encodeURIComponent,yd=function(a,b){var c=a.aa,d=a.protocol;d+=a.W?"//"+c+".fls.doubleclick.net/activityi":"//ad.doubleclick.net/activity";
d+=";src="+xd(c)+(";type="+xd(a.ba))+(";cat="+xd(a.K));var e=a.La||{},f;for(f in e)e.hasOwnProperty(f)&&(d+=";"+xd(f)+"="+xd(e[f]+""));wd(function(a,b){e.hasOwnProperty(a)||(d+=";"+a+"="+xd(b+""))},a)?(d+=b,a.W?Ca(d,a.V):Da(d,a.V,a.U)):U(a.U)};var zd=/^\w+$/,Ad=/^[\w-]+$/,Bd=/^\d+\.fls\.doubleclick\.net$/;function Cd(a){return a&&"string"==typeof a&&a.match(zd)?a:"_gcl"}function Dd(a){if(a){if("string"==typeof a){var b=Cd(a);return{M:b,L:b}}if(a&&"object"==typeof a)return{M:Cd(a.dc),L:Cd(a.aw)}}return{M:"_gcl",L:"_gcl"}}function Ed(a){var b=Ka(Q.location.href),c=Ia(b,"host",!1);if(c&&c.match(Bd)){var d=Ia(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function Fd(a){for(var b=[],c=td(a),d=0;d<c.length;d++){var e=c[d].split(".");3==e.length&&"GCL"==e[0]&&e[2].match(Ad)&&b.push(e[2])}return b}var Hd=function(a){var b=Ed("gclaw");if(b)return b.split(".");var c=Dd(a);if("_gcl"==c.L){var d=Gd();if(d&&(null==d.v||"aw.ds"==d.v))return[d.O]}return Fd(c.L+"_aw")},Id=function(a){var b=Ed("gcldc");if(b)return b.split(".");var c=Dd(a);if("_gcl"==c.M){var d=Gd();if(d&&("ds"==d.v||"aw.ds"==d.v))return[d.O]}return Fd(c.M+"_dc")};
function Gd(){var a=Ka(Q.location.href),b=Ia(a,"query",!1,void 0,"gclid"),c=Ia(a,"query",!1,void 0,"gclsrc");if(!b||!c){var d=Ia(a,"fragment");b=b||Ha(d,"gclid");c=c||Ha(d,"gclsrc")}return void 0!==b&&b.match(Ad)?{O:b,v:c}:null}
var Kd=function(){var a=Ed("gac");if(a)return decodeURIComponent(a);for(var b=[],c=R.cookie.split(";"),d=0;d<c.length;d++){var e=c[d].match(Jd);e&&3==e.length&&b.push({ea:e[1],value:e[2]})}var f={};if(b&&0!=b.length)for(var g=0;g<b.length;g++){var h=b[g].value.split(".");"1"==h[0]&&3==h.length&&h[1]&&(f[b[g].ea]||(f[b[g].ea]=[]),f[b[g].ea].push({timestamp:h[1],O:h[2]}))}var p=[],l;for(l in f)if(f.hasOwnProperty(l)){for(var n=[],k=f[l],q=0;q<k.length;q++)n.push(k[q].O);p.push(l+":"+n.join(","))}return p.join(";")},
Jd=/^\s*_gac_(UA-\d+-\d+)=\s*(.+)\s*$/;var Ld;a:{Ld="g";break a;Ld="G"}var Md={"":"n",UA:"u",AW:"a",DC:"d",GTM:Ld},Nd=function(a){var b=Kb.I.split("-"),c=b[0].toUpperCase();return(Md[c]||"i")+"b7"+(a&&"GTM"===c?b[1]:"")};var Qd="www.googletagmanager.com/gtm.js";Qd="www.googletagmanager.com/gtag/js";
var Rd=Qd,Sd=function(a,b){Ea(a,"DOMNodeInserted",b,void 0)},Td=function(a,b,c){Aa(a,b,c)},Ud={},Vd=function(a,b,c){var d=Ud[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.ya:a.la,d=0;d<c.length;d++)Q.setTimeout(c[d],0)}};d={status:1,ya:[],la:[],nb:void 0};d.vb=Aa(a,e(d,2),e(d,3));Ud[a]=d}0===d.status&&(d.nb(),d.status=2);2===d.status?b&&b():3===d.status?c&&c():1===d.status&&(b&&d.ya.push(b),c&&d.la.push(c))},Y=function(a,b,c){b&&(void 0===Q[a]||c&&!Q[a])&&(Q[a]=
b);return Q[a]},Wd=function(a){var b=void 0,c=void 0,d=Dd(a);c=c||"auto";b=b||"/";var e=Gd();if(null!=e){var f=(new Date).getTime(),g=new Date(f+7776E6),h=["GCL",Math.round(f/1E3),e.O].join(".");e.v&&"aw.ds"!=e.v||ud(d.L+"_aw",h,b,c,g);"aw.ds"!=e.v&&"ds"!=e.v||ud(d.M+"_dc",h,b,c,g)}},Yd=function(a,b,c,d){var e=!d&&"http:"==Q.location.protocol;e&&(e=2!==Xd());return(e?b:a)+c};
var $d=void 0,ae=function(a){if(!$d){var b=function(){var a=R.body;if(a)if(Y("MutationObserver"))(new MutationObserver(function(){for(var a=0;a<$d.length;a++)U($d[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;Sd(a,function(){b||(b=!0,U(function(){b=!1;for(var a=0;a<$d.length;a++)U($d[a])}))})}};$d=[];R.body?b():U(b)}$d.push(a)},Xd=function(){var a=Rd;a=a.toLowerCase();for(var b="https://"+a,c="http://"+a,d=1,e=R.getElementsByTagName("script"),f=0;f<e.length&&100>f;f++){var g=e[f].src;
if(g){g=g.toLowerCase();if(0===g.indexOf(c))return 3;1===d&&0===g.indexOf(b)&&(d=2)}}return d};var be=function(a,b){return sc(a,b,void 0)};var Z={};(function(){(function(a){Z.__e=a;Z.__e.g="e";Z.__e.i=["google"];Z.__e.h=!0})(function(){return Mb})})();
(function(){(function(a){Z.__v=a;Z.__v.g="v";Z.__v.i=["google"];Z.__v.h=!0})(function(a){var b,c=a.vtp_name.replace(/\\\./g,".");b=X(c,a.vtp_dataLayerVersion||1);return void 0!==b?b:a.vtp_defaultValue})})();
(function(){var a=!1,b=[],c="send_to aw_remarketing aw_remarketing_only custom_params send_page_view language value currency transaction_id user_id conversion_linker conversion_cookie_prefix".split(" "),d=function(a){var b=Y("google_trackConversion"),c=a.gtm_onFailure;"function"==typeof b?b(a)||c():c()},e=function(){for(;0<b.length;)d(b.shift())},f=function(){a||(a=!0,Td(Yd("https://","http://","www.googleadservices.com/pagead/conversion_async.js"),function(){e();b={push:d}},function(){e();a=!1}))},
g=/^AW-([^-/]+)(?:[-/](.*))?$/;(function(a){Z.__gtagaw=a;Z.__gtagaw.g="gtagaw";Z.__gtagaw.i=["google"];Z.__gtagaw.h=!0})(function(a){var d=g.exec(a.vtp_conversionId);if(d){var e="gtag.config"==Mb,h=d[1],k=d[2],q=void 0!==k;if(!e||!q){var w=function(a){return sc(a,"AW-"+h,void 0)},B=!1!==w("conversion_linker"),v=w("conversion_cookie_prefix");e&&B&&Wd(v);var S=!1===w("aw_remarketing")||!1===w("send_page_view");if(!e||!S){!0===w("aw_remarketing_only")&&(q=!1);var L={google_conversion_id:h,google_remarketing_only:!q,
onload_callback:a.vtp_gtmOnSuccess,gtm_onFailure:a.vtp_gtmOnFailure,google_conversion_format:"3",google_conversion_color:"ffffff",google_conversion_domain:"",google_conversion_label:k,google_conversion_language:w("language"),google_conversion_value:w("value"),google_conversion_currency:w("currency"),google_conversion_order_id:w("transaction_id"),google_user_id:w("user_id"),google_gtm:Nd(void 0),google_read_gcl_cookie_opt_out:!B};B&&v&&(E(v)?L.google_gcl_cookie_prefix=v.aw:L.google_gcl_cookie_prefix=
v);var ba=function(){var a=w("custom_params"),b={event:Mb};if(z(a)){for(var d=0;d<a.length;++d){var e=a[d],f=w(e);void 0!==f&&(b[e]=f)}return b}var g=w("eventModel");if(!g)return null;G(g,b);for(var h=0;h<c.length;++h)delete b[c[h]];return b}();ba&&(L.google_custom_params=ba);b.push(L)}f()}}})})();
(function(){function a(a){var b=/^DC-(\d+)(\/([\w-]+)\/([\w-]+)\+(\w+))?$/.exec(a);if(b){var c={standard:2,unique:3,per_session:4,transactions:5,items_sold:6,"":1}[(b[5]||"").toLowerCase()];if(c)return{ia:"DC-"+b[1],za:b[3]?a:"",Da:b[1],Aa:b[3]||"",K:b[4]||"",m:c}}}function b(a,b,c){function d(a,c,d){void 0!==d&&0!==(d+"").length&&e.push(a+c+":"+b(d+""))}var e=[],f=c("items")||[];if(z(f)&&0<f.length){for(var l=0;l<f.length;l++){var n=f[l],k=l+1;d("i",k,n.id);d("p",k,n.price);d("q",k,n.quantity);d("c",
k,c("country"));d("l",k,c("language"))}a("prd",e.join("|"),!0)}}function c(a,b,c,g){var d=b("custom_map")||{},e=vc(c,g),f={};if(E(d))for(var n in d)if(d.hasOwnProperty(n)&&/^u([1-9]\d?|100)$/.test(n)){var k=d[n];Qb(k)&&(f[n]=k)}for(var q=0;q<e.length;q++){var w=e[q];/^u([1-9]\d?|100)$/.test(w)&&(f[w]=w)}for(var B in f)if(f.hasOwnProperty(B)){var v=b(f[B]);void 0!==v&&0!==(v+"").length&&a(B,v)}}(function(a){Z.__gtagfl=a;Z.__gtagfl.g="gtagfl";Z.__gtagfl.i=[];Z.__gtagfl.h=!0})(function(d){function e(a,
b,c){w.hasOwnProperty(a)||B.hasOwnProperty(a)||(q+=";"+a+"="+(c?b:f(b)),w[a]=0)}var f=md,g=d.vtp_gtmOnSuccess,h=d.vtp_gtmOnFailure,p=a(d.vtp_targetId);if(p){var l=function(a){return sc(a,p.ia,p.za||void 0)},n=!1!==l("conversion_linker"),k=l("conversion_cookie_prefix");if("gtag.config"===Mb)n&&Wd(k),U(g);else{var q="",w={},B={},v=l("dc_custom_params");if(E(v))for(var S in v)if(v.hasOwnProperty(S)){var L=v[S];void 0!==L&&null!==L&&(B[S]=L)}5!==p.m&&6!==p.m||b(e,f,l);e("gtm",Nd(void 0));if(n){var ba=
Id(k);ba&&ba.length&&e("gcldc",ba.join("."));var A=Hd(k);A&&A.length&&e("gclaw",A.join("."));var O=Kd();O&&e("gac",O)}c(e,l,p.ia,p.za);e("~oref",Ja(Ka(Q.location.href)));q+="?";var T=3===Xd(),y=!0===l("allow_custom_scripts"),x={m:p.m,protocol:T?"http:":"https:",W:y,aa:p.Da,ba:p.Aa,K:p.K,V:g,U:h,La:B,sessionId:l("session_id"),fa:l("transaction_id"),Y:l("value"),va:l("quantity")};yd(x,q)}}else U(h)})})();
(function(){var a,b={client_id:1,client_storage:"storage",cookie_name:1,cookie_domain:1,cookie_expires:1,cookie_update:1,sample_rate:1,site_speed_sample_rate:1,use_amp_client_id:1,store_gac:1,conversion_linker:"storeGac"},c={anonymize_ip:1,app_id:1,app_installer_id:1,app_name:1,app_version:1,campaign:{name:"campaignName",source:"campaignSource",medium:"campaignMedium",term:"campaignTerm",content:"campaignContent",id:"campaignId"},currency:"currencyCode",description:"exDescription",fatal:"exFatal",
language:1,non_interaction:1,page_hostname:"hostname",page_referrer:"referrer",page_path:"page",page_title:"title",screen_name:1,transport_type:"transport",user_id:1},d={content_id:1,event_category:1,event_action:1,event_label:1,link_attribution:1,linker:1,method:1,name:1,send_page_view:1,value:1},e={cookie_name:1,cookie_expires:"duration",levels:1},f={anonymize_ip:1,fatal:1,non_interaction:1,use_amp_client_id:1,send_page_view:1,store_gac:1,conversion_linker:1},g=function(a,b,c,d){if(void 0!==c)if(f[b]&&
(c=Ub(c)),"anonymize_ip"!=b||c||(c=void 0),1===a)d[h(b)]=c;else if(Qb(a))d[a]=c;else for(var e in a)a.hasOwnProperty(e)&&void 0!==c[e]&&(d[a[e]]=c[e])},h=function(a){return a&&Qb(a)?a.replace(/(_[a-z])/g,function(a){return a[1].toUpperCase()}):a},p=function(a,b,c){a.hasOwnProperty(b)||(a[b]=c)},l=function(a,e,f){var h={},k={},n={},l=be("custom_map",a);if(E(l))for(var v in l)if(l.hasOwnProperty(v)&&/^(dimension|metric)\d+$/.test(v)){var w=be(l[v],a);void 0!==w&&p(k,v,w)}for(var q=vc(a,void 0),x=0;x<
q.length;++x){var r=q[x],M=be(r,a);d.hasOwnProperty(r)?g(d[r],r,M,h):c.hasOwnProperty(r)?g(c[r],r,M,k):b.hasOwnProperty(r)?g(b[r],r,M,n):/^(dimension|metric|content_group)\d+$/.test(r)&&g(1,r,M,k)}var K=String(Mb);p(n,"cookieDomain","auto");p(k,"forceSSL",!0);var F="general";0<=qd("add_payment_info add_to_cart add_to_wishlist begin_checkout checkout_progress purchase refund remove_from_cart set_checkout_option".split(" "),K)?F="ecommerce":0<=qd("generate_lead login search select_content share sign_up view_item view_item_list view_promotion view_search_results".split(" "),
K)?F="engagement":"exception"==K&&(F="error");p(h,"eventCategory",F);0<=qd(["view_item","view_item_list","view_promotion","view_search_results"],K)&&p(k,"nonInteraction",!0);"login"==K||"sign_up"==K||"share"==K?p(h,"eventLabel",be("method",a)):"search"==K||"view_search_results"==K?p(h,"eventLabel",be("search_term",a)):"select_content"==K&&p(h,"eventLabel",be("content_type",a));var B=h.linker||{};if(B.accept_incoming||0!=B.accept_incoming&&B.domains)n.allowLinker=!0;!1===be("allow_display_features",
a)&&(k.displayFeaturesTask=null);n.name=e;k["&gtm"]=Nd(!0);k.hitCallback=f;h.u=k;h.ja=n;return h},n=function(a){function b(a){var b=G(a,void 0);b.list=a.list_name;b.listPosition=a.list_position;b.position=a.list_position||a.creative_slot;b.creative=a.creative_name;return b}function c(a){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&c.push(b(a[d]));return c.length?c:void 0}function d(){return{id:e("transaction_id"),affiliation:e("affiliation"),revenue:e("value"),tax:e("tax"),shipping:e("shipping"),coupon:e("coupon"),
list:e("list_name")}}var e=function(b){return sc(b,a,void 0)},f=e("items"),g=e("custom_map");if(E(g))for(var h=0;f&&h<f.length;++h){var k=f[h],n;for(n in g)g.hasOwnProperty(n)&&/^(dimension|metric)\d+$/.test(n)&&p(k,n,k[g[n]])}var l=null,r=Mb,q=e("promotions");"purchase"==r||"refund"==r?l={action:r,J:d(),G:c(f)}:"add_to_cart"==r?l={action:"add",G:c(f)}:"remove_from_cart"==r?l={action:"remove",G:c(f)}:"view_item"==r?l={action:"detail",J:d(),G:c(f)}:"view_item_list"==r?l={action:"impressions",Za:c(f)}:
"view_promotion"==r?l={action:"promo_view",da:c(q)}:"select_content"==r&&q&&0<q.length?l={action:"promo_click",da:c(q)}:"select_content"==r?l={action:"click",J:{list:e("list_name")},G:c(f)}:"begin_checkout"==r||"checkout_progress"==r?l={action:"checkout",G:c(f),J:{step:"begin_checkout"==r?1:e("checkout_step"),option:e("checkout_option")}}:"set_checkout_option"==r&&(l={action:"checkout_option",J:{step:e("checkout_step"),option:e("checkout_option")}});l&&(l.ub=e("currency"));return l},k={},q=function(a,
b){var c=k[a];k[a]=G(b,void 0);if(!c)return!1;for(var d in b)if(b.hasOwnProperty(d)&&b[d]!==c[d])return!0;for(d in c)if(c.hasOwnProperty(d)&&c[d]!==b[d])return!0;return!1};(function(a){Z.__gtagua=a;Z.__gtagua.g="gtagua";Z.__gtagua.i=["google"];Z.__gtagua.h=!0})(function(b){var c=b.vtp_trackingId;Y("GoogleAnalyticsObject","ga",!0);var d=function(){return Y("GoogleAnalyticsObject")},f=Y(d(),function(){var a=Y(d());a.q=a.q||[];a.q.push(arguments)},!0);f.l=Number(new Date);var k="gtag_"+c.split("-").join("_"),
w=k+".",A=function(a){var b=[].slice.call(arguments,0);b[0]=w+b[0];Y(d()).apply(window,b)},O=function(){var a=function(a,b){for(var c=0;b&&c<b.length;c++)A(a,b[c])},b=n(c);if(b){var d=b.action;if("impressions"==d)a("ec:addImpression",b.Za);else if("promo_click"==d||"promo_view"==d){var e=b.da;a("ec:addPromo",b.da);e&&0<e.length&&"promo_click"==d&&A("ec:setAction",d)}else a("ec:addProduct",b.G),A("ec:setAction",d,b.J)}},T=function(){var a=be("optimize_id",c);a&&(A("require",a,{dataLayer:"dataLayer"}),
A("require","render"))},y=l(c,k,b.vtp_gtmOnSuccess);q(k,y.ja)&&f(function(){Y(d()).remove(k)});f("create",c,y.ja);(function(){var a=be("custom_map",c);f(function(){if(E(a)){var b=y.u,c=Y(d()).getByName(k),e;for(e in a)if(a.hasOwnProperty(e)&&/^(dimension|metric)\d+$/.test(e)){var f=c.get(h(a[e]));p(b,e,f)}}})})();(function(a){if(a){var b={};if(E(a))for(var c in e)e.hasOwnProperty(c)&&g(e[c],c,a[c],b);A("require","linkid",b)}})(y.linkAttribution);(function(a){var b=a&&a.domains;if(Qb(b)||z(b)){var c=
b.toString().replace(/\s+/g,"");c.length&&(A("require","linker"),A("linker:autoLink",c.split(","),!!a.use_anchor,!!a.decorate_forms))}})(y.linker);var x=function(a,b,c){c&&(b=""+b);y.u[a]=b},r=Mb;"page_view"==r?(T(),A("send","pageview",y.u)):"gtag.config"==r?0!=y.sendPageView&&(T(),A("send","pageview",y.u)):"screen_view"==r?A("send","screenview",y.u):"timing_complete"==r?(x("timingCategory",y.eventCategory,!0),x("timingVar",y.name,!0),x("timingValue",Tb(y.value)),void 0!==y.eventLabel&&x("timingLabel",
y.eventLabel,!0),A("send","timing",y.u)):"exception"==r?A("send","exception",y.u):(0<=qd("view_item_list select_content view_item add_to_cart remove_from_cart begin_checkout set_checkout_option purchase refund view_promotion checkout_progress".split(" "),r)&&(A("require","ec","ec.js"),O()),x("eventCategory",y.eventCategory,!0),x("eventAction",y.eventAction||r,!0),void 0!==y.eventLabel&&x("eventLabel",y.eventLabel,!0),void 0!==y.value&&x("eventValue",Tb(y.value)),A("send","event",y.u));a||(a=!0,Td("https://www.google-analytics.com/analytics.js",
function(){Y(d()).loaded||b.vtp_gtmOnFailure()},b.vtp_gtmOnFailure))})})();var ce={macro:function(){}};ce.dataLayer=rc;ce.callback=function(a){Nb.hasOwnProperty(a)&&Pb(Nb[a])&&Nb[a]();delete Nb[a]};ce.Fa=function(){var a=Q.google_tag_manager;a||(a=Q.google_tag_manager={});a[Kb.I]||(a[Kb.I]=ce);Lb=a};for(var de=data.resource||{},ee=de.macros||[],fe=0;fe<ee.length;fe++)xb.push(ee[fe]);var ge=de.tags||[];for(fe=0;fe<ge.length;fe++)Ab.push(ge[fe]);var he=de.predicates||[];for(fe=0;fe<he.length;fe++)zb.push(he[fe]);
for(var ie=de.rules||[],je=0;je<ie.length;je++){for(var ke=ie[je],le={},me=0;me<ke.length;me++)le[ke[me][0]]=Array.prototype.slice.call(ke[me],1);yb.push(le)}Bb=Z;(function(a){wb=function(a){return kd.f(a)};Gb=Yc;Ma(kd,jd());for(var b=0;b<a.length;b++){var c=a[b];if(!z(c)||3>c.length){if(0==c.length)continue;dc("Internal Error");break}kd.f(c)}})(data.runtime||[]);ce.Fa();
(function(){var a=xa("dataLayer",[]),b=xa("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};kc.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Qc.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Sc.push.apply(Sc,b);300<this.length;)this.shift();return Vc()};Sc.push.apply(Sc,a.slice(0));U(Wc)})();ic=!1;jc=0;
if("interactive"==R.readyState&&!R.createEventObject||"complete"==R.readyState)lc();else{Ea(R,"DOMContentLoaded",lc);Ea(R,"readystatechange",lc);if(R.createEventObject&&R.documentElement.doScroll){var ne=!0;try{ne=!Q.frameElement}catch(a){}ne&&mc()}Ea(Q,"load",lc)}Pc=!1;"complete"===R.readyState?Rc():Ea(Q,"load",Rc);

})()
